# Generated by Django 2.2.5 on 2022-01-24 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='name')),
                ('picture', models.ImageField(upload_to='houses')),
                ('description', models.TextField(verbose_name='detail')),
                ('area', models.FloatField(verbose_name='area')),
                ('price', models.FloatField(verbose_name='price(permonth)')),
                ('position', models.CharField(max_length=64, verbose_name='position')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='online time')),
                ('status', models.CharField(choices=[('wait to rent', 'wait to rent'), ('rented', 'rented')], default='wait to rent', max_length=32, verbose_name='status')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
            ],
            options={
                'verbose_name': 'house',
                'verbose_name_plural': 'house',
                'ordering': ('-create_at',),
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='rent time')),
                ('months', models.IntegerField(default=1, verbose_name='rent_months')),
                ('deadline', models.DateField(verbose_name='deadline')),
                ('money', models.FloatField(default=0, verbose_name='total money')),
                ('status', models.CharField(choices=[('normal', 'normal'), ('apply to unsubscribe', 'apply to unsubscribe'), ('unsubscribed', 'unsubscribed'), ('delayed', 'delayed')], default='normal', max_length=32, verbose_name='status')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.House', verbose_name='House')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h_rent_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'rent',
                'verbose_name_plural': 'rent',
                'ordering': ('-create_at',),
            },
        ),
        migrations.CreateModel(
            name='Tongji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Statistics',
            },
        ),
        migrations.CreateModel(
            name='Unsubscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='rent time')),
                ('status', models.CharField(choices=[('wait to approve', 'wait to approve'), ('approve', 'approve')], max_length=32, verbose_name='status')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('is_from_delay', models.BooleanField(default=False, verbose_name='is from delay')),
                ('rent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='house.Rent', verbose_name='rent info')),
            ],
            options={
                'verbose_name': 'subscribe',
                'verbose_name_plural': 'subscribe',
                'ordering': ('-create_at',),
            },
        ),
        migrations.CreateModel(
            name='Delay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('months', models.IntegerField(default=1, verbose_name='rent_months')),
                ('deadline', models.DateField(verbose_name='deadline')),
                ('money', models.FloatField(default=0, verbose_name='total money')),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.Rent', verbose_name='rent info')),
            ],
            options={
                'verbose_name': 'delay',
                'verbose_name_plural': 'delay',
                'ordering': ('-create_at',),
            },
        ),
    ]
